import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { Avatar, Divider, EmptyState, IconButton, SectionTitle, StatusPill, palette } from "@/components/luma-primitives";
import { ScreenContainer } from "@/components/screen-container";
import { useWorkroom } from "@/lib/workroom-store";

export default function ActivityScreen() {
  const { approvals, bots, activity, notifications, resolveApproval, markNotificationsRead } = useWorkroom();
  const pendingApprovals = approvals.filter((approval) => approval.state === "Pending");
  const unreadCount = notifications.filter((notification) => !notification.read).length;

  return <ScreenContainer containerClassName="bg-background" className="flex-1" edges={["top", "left", "right"]}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.head}><View><Text style={styles.title}>Updates</Text><Text style={styles.lead}>The moments where your work needs you, in one quiet place.</Text></View><IconButton icon="done-all" label="Mark notifications read" onPress={markNotificationsRead} tone={unreadCount ? "mint" : "default"} /></View>
      <SectionTitle eyebrow="Decisions" title={pendingApprovals.length ? `${pendingApprovals.length} need you` : "Nothing needs you"} />
      {pendingApprovals.length ? <View style={styles.cards}>{pendingApprovals.map((approval) => { const bot = bots.find((entry) => entry.id === approval.botId); return <View key={approval.id} style={styles.approvalCard}><View style={styles.approvalHead}><View style={styles.approvalIdentity}>{bot ? <Avatar label={bot.avatar} color={bot.color} size={36} /> : null}<View style={styles.approvalCopy}><Text style={styles.cardTitle}>{approval.title}</Text><Text style={styles.cardMeta}>{bot?.name ?? "Bot"} · {approval.createdAt}</Text></View></View><StatusPill label={`${approval.risk} risk`} tone="amber" /></View><Text style={styles.cardDetail}>{approval.detail}</Text><View style={styles.approvalActions}><Pressable accessibilityRole="button" onPress={() => resolveApproval(approval.id, "Declined")} style={({ pressed }) => [styles.declineButton, pressed && styles.pressed]}><Text style={styles.declineText}>Decline</Text></Pressable><Pressable accessibilityRole="button" onPress={() => resolveApproval(approval.id, "Approved")} style={({ pressed }) => [styles.approveButton, pressed && styles.pressed]}><MaterialIcons name="check" size={17} color="#FFFFFF" /><Text style={styles.approveText}>Approve</Text></Pressable></View></View>; })}</View> : <EmptyState icon="verified-user" title="Nothing needs a decision" detail="When a Bot reaches a pause point you set, its request will appear here." />}
      <SectionTitle eyebrow="Timeline" title="What moved" />
      {activity.length ? <View style={styles.timeline}>{activity.map((entry, index) => <View key={entry.id} style={styles.timelineRow}><View style={styles.timelineRail}><View style={[styles.timelineDot, entry.tone === "amber" && { backgroundColor: palette.amber }, entry.tone === "coral" && { backgroundColor: palette.coral }, entry.tone === "muted" && { backgroundColor: palette.mist }]} />{index < activity.length - 1 ? <View style={styles.timelineLine} /> : null}</View><View style={styles.timelineCopy}><Text style={styles.timelineTitle}>{entry.title}</Text><Text style={styles.timelineDetail}>{entry.detail}</Text><Text style={styles.timelineTime}>{entry.createdAt}</Text></View></View>)}</View> : <EmptyState icon="timeline" title="Your timeline is clear" detail="Creating a Bot and giving it work will start a real activity trail." />}
      <SectionTitle eyebrow="Alerts" title={unreadCount ? `${unreadCount} unread` : "All caught up"} />
      {notifications.length ? <View style={styles.notificationCard}>{notifications.map((notification, index) => <View key={notification.id}>{index ? <Divider /> : null}<View style={styles.notificationRow}><View style={[styles.notificationIcon, notification.tone === "amber" && styles.notificationAmber, notification.tone === "coral" && styles.notificationCoral]}><MaterialIcons name={notification.tone === "amber" ? "priority-high" : notification.tone === "coral" ? "error-outline" : "check-circle-outline"} size={18} color={notification.tone === "amber" ? palette.amber : notification.tone === "coral" ? palette.coral : palette.mint} /></View><View style={styles.notificationCopy}><Text style={[styles.cardTitle, !notification.read && styles.notificationUnread]}>{notification.title}</Text><Text style={styles.cardMeta}>{notification.detail}</Text></View><Text style={styles.noticeTime}>{notification.createdAt}</Text></View></View>)}</View> : <EmptyState icon="notifications-none" title="No alerts yet" detail="Task completions and approval requests will appear here after you start work." />}
    </ScrollView>
  </ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 30, gap: 21, maxWidth: 780, width: "100%", alignSelf: "center" }, head: { flexDirection: "row", justifyContent: "space-between", gap: 14 }, title: { color: palette.cloud, fontSize: 25, fontWeight: "900", letterSpacing: -0.7, lineHeight: 31 }, lead: { color: palette.mist, fontSize: 13, lineHeight: 19, marginTop: 5, maxWidth: 300 }, cards: { gap: 9 }, approvalCard: { backgroundColor: "#FFF9EE", borderWidth: 1, borderColor: "#F0D59D", borderRadius: 19, padding: 15, gap: 12 }, approvalHead: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }, approvalIdentity: { flex: 1, flexDirection: "row", alignItems: "center", gap: 9, minWidth: 0 }, approvalCopy: { flex: 1, minWidth: 0 }, cardTitle: { color: palette.cloud, fontSize: 14, lineHeight: 19, fontWeight: "800" }, cardMeta: { color: palette.mist, fontSize: 11, lineHeight: 16, marginTop: 3 }, cardDetail: { color: palette.mist, fontSize: 12, lineHeight: 18 }, approvalActions: { flexDirection: "row", gap: 9 }, declineButton: { flex: 1, alignItems: "center", borderRadius: 14, paddingVertical: 12, borderWidth: 1, borderColor: "#F1BDBD", backgroundColor: "#FFF1F1" }, declineText: { color: palette.coral, fontSize: 13, fontWeight: "800" }, approveButton: { flex: 1, flexDirection: "row", gap: 6, alignItems: "center", justifyContent: "center", borderRadius: 14, paddingVertical: 12, backgroundColor: palette.ink }, approveText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, timeline: { gap: 0, paddingLeft: 3 }, timelineRow: { flexDirection: "row", minHeight: 66 }, timelineRail: { width: 23, alignItems: "center" }, timelineDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: palette.mint, marginTop: 4 }, timelineLine: { width: 1, flex: 1, backgroundColor: palette.line, marginVertical: 4 }, timelineCopy: { flex: 1, paddingBottom: 14, paddingLeft: 7 }, timelineTitle: { color: palette.cloud, fontSize: 13, lineHeight: 18, fontWeight: "800" }, timelineDetail: { color: palette.mist, fontSize: 11, lineHeight: 16, marginTop: 3 }, timelineTime: { color: palette.mist, fontSize: 10, marginTop: 5 }, notificationCard: { backgroundColor: palette.graphite, borderWidth: 1, borderColor: palette.line, borderRadius: 19, overflow: "hidden" }, notificationRow: { flexDirection: "row", alignItems: "center", gap: 10, padding: 13 }, notificationIcon: { width: 35, height: 35, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#18B98214" }, notificationAmber: { backgroundColor: "#B7791214" }, notificationCoral: { backgroundColor: "#D65A5A14" }, notificationCopy: { flex: 1, minWidth: 0 }, notificationUnread: { color: palette.mint }, noticeTime: { color: palette.mist, fontSize: 10 }, pressed: { opacity: 0.74, transform: [{ scale: 0.98 }] },
});
